name: CI/CD TodoWam app

on:
    push:
        branches: [main]

env:
    PROJECT_NAME: TodoWam

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install dependencies
              run : |
                npm install
            
            - name: Run tests
              run : |
                npm test -- --watchAll=false